meta_product_name: "Vetonde"
meta_title: "Vetonde - Vet on demand"
meta_description: "Chat with Vet in seconds. Vetonde is everything you need if you own animal."
meta_image: "cover.webp" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
